import { AppKit } from "@circle-fin/app-kit";
import type { SwapEstimate, SwapParams, SwapResult } from "@circle-fin/app-kit";
import { createViemAdapterFromProvider } from "@circle-fin/adapter-viem-v2";
import { createPublicClient, formatUnits, http } from "viem";
import type { EIP1193Provider } from "viem";
import { ARC_TESTNET, ARC_TESTNET_CHAIN } from "./arc-network";
import { assertWalletContext, escapeHtml, safeExplorerUrl, validTokenAmount } from "./browser-security";

declare global { interface Window { ethereum?: EIP1193Provider; } }
const arc = ARC_TESTNET_CHAIN;
const tokens = { USDC: ARC_TESTNET.tokens.USDC, EURC: ARC_TESTNET.tokens.EURC } as const;
const abi = [{ type: "function", name: "balanceOf", stateMutability: "view", inputs: [{ name: "account", type: "address" }], outputs: [{ type: "uint256" }] }] as const;
const kit = new AppKit(); const client = createPublicClient({ chain: arc, transport: http() }); let adapter: Awaited<ReturnType<typeof createViemAdapterFromProvider>> | null = null; let address = "";
function routeStablecoinServiceThroughLocalProxy(): void { const originalFetch = globalThis.fetch.bind(globalThis); globalThis.fetch = (input: RequestInfo | URL, init?: RequestInit) => { const rawUrl = typeof input === "string" ? input : input instanceof URL ? input.toString() : input.url; if (rawUrl.startsWith("https://api.circle.com/v1/stablecoinKits/")) { const upstream = new URL(rawUrl); if (location.hostname === "localhost" || location.hostname === "127.0.0.1") return originalFetch(`/circle-api${upstream.pathname}${upstream.search}`, init); const query = new URLSearchParams(upstream.search); query.set("service", "stablecoin"); query.set("target", upstream.pathname.replace(/^\/+/, "")); return originalFetch(`/api/circle-proxy?${query.toString()}`, init); } return originalFetch(input, init); }; }
routeStablecoinServiceThroughLocalProxy();
const el = { connect: document.querySelector<HTMLButtonElement>("#connect")!, quote: document.querySelector<HTMLButtonElement>("#quote")!, execute: document.querySelector<HTMLButtonElement>("#execute")!, refresh: document.querySelector<HTMLButtonElement>("#refresh")!, kitKey: document.querySelector<HTMLInputElement>("#kitKey")!, amount: document.querySelector<HTMLInputElement>("#amount")!, from: document.querySelector<HTMLSelectElement>("#from")!, to: document.querySelector<HTMLSelectElement>("#to")!, wallet: document.querySelector<HTMLElement>("#wallet")!, usdc: document.querySelector<HTMLElement>("#usdc")!, eurc: document.querySelector<HTMLElement>("#eurc")!, status: document.querySelector<HTMLElement>("#status")!, quoteBox: document.querySelector<HTMLElement>("#quoteBox")!, resultBox: document.querySelector<HTMLElement>("#resultBox")! };
function setStatus(message: string): void { el.status.textContent = message; }
function key(): string { const value = el.kitKey.value.trim(); if (!value.startsWith("KIT_KEY:")) throw new Error("A KIT_KEY is required for App Kit FX execution."); return value; }
function params(): SwapParams { if (!adapter) throw new Error("Connect MetaMask first."); if (el.from.value === el.to.value) throw new Error("Choose different currencies."); const amount = el.amount.value.trim(); if (!validTokenAmount(amount)) throw new Error("Enter a positive amount with up to 6 decimal places."); return { from: { adapter, chain: "Arc_Testnet" }, tokenIn: el.from.value as "USDC" | "EURC", tokenOut: el.to.value as "USDC" | "EURC", amountIn: amount, config: { kitKey: key(), slippageBps: 100, allowanceStrategy: "approve" } }; }
async function balance(symbol: keyof typeof tokens): Promise<string> { const token = tokens[symbol]; const value = await client.readContract({ address: token.address as `0x${string}`, abi, functionName: "balanceOf", args: [address as `0x${string}`] }); return formatUnits(value, token.decimals); }
async function refresh(): Promise<void> { if (!address) return; const [usdc, eurc] = await Promise.all([balance("USDC"), balance("EURC")]); el.usdc.textContent = `${usdc} USDC`; el.eurc.textContent = `${eurc} EURC`; }
async function connect(): Promise<void> { if (!window.ethereum) throw new Error("MetaMask provider not found."); await window.ethereum.request({ method: "wallet_switchEthereumChain", params: [{ chainId: ARC_TESTNET.chainIdHex }] }); const accounts = await window.ethereum.request({ method: "eth_requestAccounts" }) as string[]; address = accounts[0] ?? ""; adapter = await createViemAdapterFromProvider({ provider: window.ethereum }); el.wallet.textContent = address; el.quote.disabled = false; el.execute.disabled = false; el.refresh.disabled = false; await refresh(); setStatus("Wallet connected. Enter a TEST KIT_KEY to request an FX quote."); }
function renderQuote(value: SwapEstimate): void { el.quoteBox.innerHTML = `<div><strong>Pair</strong><span>${escapeHtml(`${value.estimatedOutput.token} received for ${value.stopLimit.token} sold`)}</span></div><div><strong>Estimated output</strong><span>${escapeHtml(`${value.estimatedOutput.amount} ${value.estimatedOutput.token}`)}</span></div><div><strong>Stop limit</strong><span>${escapeHtml(`${value.stopLimit.amount} ${value.stopLimit.token}`)}</span></div><div><strong>Fees</strong><span>${escapeHtml(value.fees?.map((fee) => `${fee.type}: ${fee.amount} ${fee.token}`).join(", ") || "-")}</span></div>`; }
function renderResult(value: SwapResult): void { const fallback = `${ARC_TESTNET.explorerUrl}/tx/${value.txHash}`; const receiptUrl = safeExplorerUrl(value.explorerUrl, fallback, "testnet.arcscan.app"); el.resultBox.innerHTML = `<div><strong>Input</strong><span>${escapeHtml(`${value.amountIn} ${value.tokenIn}`)}</span></div><div><strong>Output</strong><span>${escapeHtml(`${value.amountOut ?? "-"} ${value.tokenOut}`)}</span></div><div><strong>Transaction</strong><span>${escapeHtml(value.txHash)}</span></div><a href="${escapeHtml(receiptUrl)}" target="_blank" rel="noreferrer">View ArcScan receipt</a>`; localStorage.setItem("ArcStablecoinFX.lastTrade", JSON.stringify(value, (_key, entry) => typeof entry === "bigint" ? entry.toString() : entry)); }
async function verifyWallet(): Promise<void> { if (!window.ethereum || !address) throw new Error("Connect MetaMask first."); await assertWalletContext(window.ethereum, ARC_TESTNET.chainIdHex, address); }
async function estimate(): Promise<void> { if (!adapter) await connect(); setStatus("Requesting FX quote..."); try { await verifyWallet(); renderQuote(await kit.estimateSwap(params())); setStatus("Quote ready. No transaction submitted."); } catch (error) { setStatus(`Quote failed: ${error instanceof Error ? error.message : "Unknown error."}`); } }
async function execute(): Promise<void> { if (!adapter) await connect(); el.execute.disabled = true; try { await verifyWallet(); setStatus("Waiting for MetaMask approval and swap signature..."); const value = await kit.swap(params()); renderResult(value); await refresh(); setStatus("FX swap confirmed."); } catch (error) { setStatus(`FX execution failed: ${error instanceof Error ? error.message : "Unknown error."}`); } finally { el.execute.disabled = false; } }
el.connect.addEventListener("click", () => void connect().catch((error) => setStatus(error instanceof Error ? error.message : "Connection failed."))); el.quote.addEventListener("click", () => void estimate()); el.execute.addEventListener("click", () => void execute()); el.refresh.addEventListener("click", () => void refresh());
